project_id = "oyjwexbyxggotuuxxisq"

[functions.generate-marketing-materials]
verify_jwt = false

[functions.classify-intent]
verify_jwt = false

[functions.chat-agent]
verify_jwt = false

[functions.build-agent]
verify_jwt = false

[functions.plan-agent]
verify_jwt = false

[functions.analyze-code-quality]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.requirements-agent]
verify_jwt = false

[functions.backend-agent]
verify_jwt = false

[functions.project-api]
verify_jwt = false

[functions.project-auth]
verify_jwt = false

[functions.project-exec]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.project-name]
verify_jwt = false

[functions.review-code]
verify_jwt = false

[functions.cloudflare-dns]
verify_jwt = false

[functions.generate-brand-kit]
verify_jwt = false

[functions.github-api]
verify_jwt = false

[functions.ui-kit]
verify_jwt = false

[functions.analyze-prompt]
verify_jwt = false

[functions.project-email]
verify_jwt = false

[functions.build-orchestrator]
verify_jwt = false

[functions.build-preview]
verify_jwt = false

[functions.android-export]
verify_jwt = false

[functions.project-db]
verify_jwt = false

[functions.container-build]
verify_jwt = false

[functions.container-status]
verify_jwt = false
