import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");

/**
 * Backend Agent — generates data layer, SQL migrations, RLS policies,
 * and API hooks based on a domain model from the Requirements Agent.
 *
 * Task types:
 * - "schema": Generate SQL migrations, RLS policies, schema.json, and typed hooks
 * - "backend": Generate CRUD hooks, contexts, and API integration
 *
 * RULES:
 * - ALWAYS generate SQL migrations for schema tasks
 * - ALWAYS generate RLS policies for every table
 * - ALWAYS use project-api/project-auth — NEVER use localStorage for auth
 * - NEVER use mock data as primary persistence
 */

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { task, domainModel, projectId, existingFiles, techStack } = await req.json();

    if (!task || !domainModel) {
      return new Response(
        JSON.stringify({ error: "task and domainModel are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const taskType = task.taskType || "backend";
    const apiBase = `${SUPABASE_URL}/functions/v1`;

    let generatedFiles: Record<string, string> = {};
    let chatText = "";

    if (taskType === "schema") {
      // ── Schema Task: Generate SQL migrations + RLS + schema.json + hooks ──
      const result = generateSchemaFiles(domainModel, projectId, apiBase);
      generatedFiles = result.files;
      chatText = result.chatText;
    } else if (taskType === "backend") {
      // ── Backend Task: Generate hooks + contexts using real API ──
      if (LOVABLE_API_KEY) {
        const aiResult = await generateBackendWithAI(task, domainModel, projectId, apiBase, existingFiles);
        generatedFiles = aiResult.files;
        chatText = aiResult.chatText;
      } else {
        const result = generateBackendFiles(domainModel, projectId, apiBase);
        generatedFiles = result.files;
        chatText = result.chatText;
      }
    }

    // Wrap in react-preview format for the build engine parser
    const codeBlock = Object.entries(generatedFiles)
      .map(([path, code]) => `--- ${path}\n${code}`)
      .join("\n");

    const fullResponse = `${chatText}\n\n\`\`\`react-preview\n${codeBlock}\n\`\`\``;

    return new Response(
      JSON.stringify({ response: fullResponse, files: generatedFiles }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("backend-agent error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Backend agent error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

// ─── Schema File Generation (SQL migrations + RLS + schema.json + hooks) ──

function generateSchemaFiles(
  domainModel: any,
  projectId: string,
  apiBase: string
): { files: Record<string, string>; chatText: string } {
  const files: Record<string, string> = {};
  const entities = domainModel.entities || [];

  // 1. Generate SQL migrations
  let schemaSql = `-- Schema migration for project: ${projectId}\n-- Generated by Phoenix Backend Agent\n\n`;
  for (const entity of entities) {
    const tableName = entity.pluralName || entity.name.toLowerCase() + "s";
    schemaSql += `CREATE TABLE IF NOT EXISTS ${tableName} (\n`;
    schemaSql += `  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n`;
    for (const field of entity.fields || []) {
      const sqlType = fieldTypeToSql(field.type);
      const nullable = field.required ? " NOT NULL" : "";
      const defaultVal = field.default !== undefined ? ` DEFAULT ${sqlDefault(field.default, field.type)}` : "";
      schemaSql += `  ${field.name} ${sqlType}${nullable}${defaultVal},\n`;
    }
    schemaSql += `  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,\n`;
    schemaSql += `  created_at timestamptz DEFAULT now(),\n`;
    schemaSql += `  updated_at timestamptz DEFAULT now()\n`;
    schemaSql += `);\n\n`;
  }
  files["/migrations/001_schema.sql"] = schemaSql;

  // 2. Generate RLS policies
  let rlsSql = `-- Row Level Security policies\n\n`;
  for (const entity of entities) {
    const tableName = entity.pluralName || entity.name.toLowerCase() + "s";
    rlsSql += `ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;\n\n`;
    rlsSql += `CREATE POLICY "Users can view own ${tableName}" ON ${tableName}\n`;
    rlsSql += `  FOR SELECT USING (auth.uid() = user_id);\n\n`;
    rlsSql += `CREATE POLICY "Users can create own ${tableName}" ON ${tableName}\n`;
    rlsSql += `  FOR INSERT WITH CHECK (auth.uid() = user_id);\n\n`;
    rlsSql += `CREATE POLICY "Users can update own ${tableName}" ON ${tableName}\n`;
    rlsSql += `  FOR UPDATE USING (auth.uid() = user_id);\n\n`;
    rlsSql += `CREATE POLICY "Users can delete own ${tableName}" ON ${tableName}\n`;
    rlsSql += `  FOR DELETE USING (auth.uid() = user_id);\n\n`;
  }
  files["/migrations/002_rls.sql"] = rlsSql;

  // 3. Generate schema.json
  const schemaJson = {
    projectId,
    entities: entities.map((e: any) => ({
      name: e.name,
      table: e.pluralName || e.name.toLowerCase() + "s",
      fields: [
        { name: "id", type: "uuid", primary: true },
        ...(e.fields || []).map((f: any) => ({
          name: f.name,
          type: f.type,
          required: f.required || false,
          ...(f.options ? { options: f.options } : {}),
        })),
        { name: "user_id", type: "uuid", reference: "auth.users" },
        { name: "created_at", type: "timestamptz" },
        { name: "updated_at", type: "timestamptz" },
      ],
      relationships: e.relationships || [],
    })),
  };
  files["/schema.json"] = JSON.stringify(schemaJson, null, 2);

  // 4. Generate API config
  files["/data/apiConfig.js"] = `/**
 * API Configuration — connects to real backend.
 */
export const API_CONFIG = {
  projectId: typeof window !== "undefined" ? window.__PROJECT_ID__ || "${projectId}" : "${projectId}",
  apiBase: typeof window !== "undefined" ? window.__SUPABASE_URL__ || "${apiBase}" : "${apiBase}",
  anonKey: typeof window !== "undefined" ? window.__SUPABASE_KEY__ || "" : "",
};
`;

  // 5. Generate CRUD hooks for each entity (using real API, with sample fallback)
  for (const entity of entities) {
    files[`/hooks/use${entity.name}.js`] = generateHookFile(entity, projectId, apiBase);
  }

  // 6. Generate sample data as fallback only
  for (const entity of entities) {
    const records = generateSampleRecords(entity);
    files[`/data/${entity.pluralName}_samples.js`] = `/**
 * Sample data for ${entity.name} — ONLY used as fallback when API is unavailable.
 * Primary data source is the real backend via project-api.
 */
export const sample${entity.name}s = ${JSON.stringify(records, null, 2)};
`;
  }

  const entityNames = entities.map((e: any) => e.name).join(", ");
  const chatText = `✅ Generated schema layer: SQL migrations, RLS policies, schema.json, and API hooks for: ${entityNames}`;

  return { files, chatText };
}

function fieldTypeToSql(fieldType: string): string {
  switch (fieldType) {
    case "text": return "text";
    case "email": return "text";
    case "number": return "numeric";
    case "boolean": return "boolean";
    case "datetime": return "timestamptz";
    case "url": return "text";
    case "textarea": return "text";
    case "select": return "text";
    case "json": return "jsonb";
    case "phone": return "text";
    default: return "text";
  }
}

function sqlDefault(value: any, type: string): string {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  if (value === null) return "NULL";
  return `'${String(value)}'`;
}

function generateSampleRecords(entity: any): any[] {
  const records = [];
  const count = Math.min(entity.seedCount || 3, 5); // Fewer samples — just fallback data
  const names = ["Alice Johnson", "Bob Smith", "Carol Williams", "David Brown", "Eve Davis"];
  const companies = ["Acme Corp", "TechVentures", "GlobalSoft"];
  const subjects = ["Mathematics", "Physics", "Chemistry", "Biology", "English"];
  const departments = ["Engineering", "Marketing", "Sales", "HR", "Finance"];

  for (let i = 0; i < count; i++) {
    const record: any = { id: `sample-${entity.pluralName}-${i + 1}` };
    for (const field of entity.fields || []) {
      record[field.name] = generateValue(field, entity.name, i, names, companies, subjects, departments);
    }
    record.created_at = new Date(Date.now() - (count - i) * 86400000).toISOString();
    records.push(record);
  }
  return records;
}

function generateValue(field: any, entityName: string, i: number, names: string[], companies: string[], subjects: string[], departments: string[]): any {
  if (field.default !== undefined && field.default !== null && field.type !== "select") return field.default;
  const n = field.name.toLowerCase();
  switch (field.type) {
    case "text":
      if (n === "name" || n.includes("name")) return names[i % names.length];
      if (n.includes("phone")) return `+1 (555) ${String(100 + i).padStart(3, "0")}-${String(1000 + i * 7).slice(-4)}`;
      if (n.includes("sku")) return `SKU-${String(10000 + i * 137).slice(-5)}`;
      if (n.includes("roll") || n.includes("number")) return `${entityName.charAt(0)}${1000 + i}`;
      if (n.includes("class")) return `Class ${Math.floor(i / 3) + 1}${["A", "B", "C"][i % 3]}`;
      if (n.includes("subject")) return subjects[i % subjects.length];
      if (n.includes("department")) return departments[i % departments.length];
      if (n.includes("company")) return companies[i % companies.length];
      if (n.includes("room")) return `Room ${100 + i}`;
      if (n.includes("time")) return `${8 + Math.floor(i / 2)}:${i % 2 === 0 ? "00" : "30"}`;
      if (n.includes("tracking")) return `TRK${String(100000 + i * 997).slice(-8)}`;
      return `${entityName} ${field.name} ${i + 1}`;
    case "email": return `user${i + 1}@example.com`;
    case "number":
      if (n.includes("price") || n.includes("amount") || n.includes("cost") || n.includes("salary") || n.includes("value") || n.includes("total") || n.includes("fee")) return Math.round((Math.random() * 9000 + 1000) * 100) / 100;
      if (n.includes("rating")) return Math.round((Math.random() * 4 + 1) * 10) / 10;
      if (n.includes("probability")) return Math.floor(Math.random() * 100);
      return i + 1;
    case "boolean": return i % 3 !== 0;
    case "datetime": return new Date(Date.now() - Math.floor(Math.random() * 365) * 86400000).toISOString();
    case "url": return `https://picsum.photos/seed/${entityName.toLowerCase()}${i}/400/300`;
    case "textarea": return `Sample ${field.name} for ${entityName} #${i + 1}.`;
    case "select": return field.options ? field.options[i % field.options.length] : "default";
    case "json": return field.default || {};
    default: return `${field.name} ${i + 1}`;
  }
}

// ─── Backend File Generation (template-based) ────────────────────────────

function generateBackendFiles(
  domainModel: any,
  projectId: string,
  apiBase: string
): { files: Record<string, string>; chatText: string } {
  const files: Record<string, string> = {};

  // Generate CRUD hook for each entity
  for (const entity of domainModel.entities || []) {
    files[`/hooks/use${entity.name}.js`] = generateHookFile(entity, projectId, apiBase);
  }

  // Generate data context
  const imports = (domainModel.entities || []).map((e: any) =>
    `import { use${e.name}s } from "../hooks/use${e.name}";`
  ).join("\n");

  const contextFields = (domainModel.entities || []).map((e: any) =>
    `    ${e.pluralName}: use${e.name}s(),`
  ).join("\n");

  files["/contexts/DataContext.js"] = `import React, { createContext, useContext } from "react";
${imports}

const DataContext = createContext(null);

export function DataProvider({ children }) {
  const data = {
${contextFields}
  };
  return <DataContext.Provider value={data}>{children}</DataContext.Provider>;
}

export function useData() {
  const ctx = useContext(DataContext);
  if (!ctx) throw new Error("useData must be used within DataProvider");
  return ctx;
}
`;

  // Auth context if needed
  if (domainModel.requiresAuth) {
    files["/contexts/AuthContext.js"] = generateAuthContext(projectId, apiBase);
    files["/components/ui/ProtectedRoute.jsx"] = generateProtectedRoute();
  }

  const entityNames = (domainModel.entities || []).map((e: any) => e.name).join(", ");
  const chatText = `✅ Generated backend layer: CRUD hooks for ${entityNames}${domainModel.requiresAuth ? " + auth context" : ""}`;

  return { files, chatText };
}

function generateHookFile(entity: any, projectId: string, apiBase: string): string {
  const name = entity.name;
  const plural = entity.pluralName;

  return `import { useState, useEffect, useCallback } from "react";
import { sample${name}s } from "../data/${plural}_samples";
import { API_CONFIG } from "../data/apiConfig";

export function use${name}s() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchItems = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const resp = await fetch(API_CONFIG.apiBase + "/functions/v1/project-api", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
        body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "list", collection: "${plural}" }),
      });
      const json = await resp.json();
      setItems(json.data || []);
    } catch (err) {
      // Graceful fallback to sample data when API is unreachable
      console.warn("[use${name}s] API unreachable, using sample data:", err?.message);
      setItems([...sample${name}s]);
      setError(null); // Don't show error — show sample data instead
    } finally {
      setLoading(false);
    }
  }, []);

  const create = useCallback(async (data) => {
    try {
      const resp = await fetch(API_CONFIG.apiBase + "/functions/v1/project-api", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
        body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "create", collection: "${plural}", data }),
      });
      const json = await resp.json();
      if (json.error) throw new Error(json.error);
      setItems(prev => [json.data, ...prev]);
      return json.data;
    } catch (err) { setError(err.message); throw err; }
  }, []);

  const update = useCallback(async (id, data) => {
    try {
      const resp = await fetch(API_CONFIG.apiBase + "/functions/v1/project-api", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
        body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "update", collection: "${plural}", id, data }),
      });
      const json = await resp.json();
      if (json.error) throw new Error(json.error);
      setItems(prev => prev.map(item => item.id === id ? { ...item, ...json.data } : item));
      return json.data;
    } catch (err) { setError(err.message); throw err; }
  }, []);

  const remove = useCallback(async (id) => {
    try {
      await fetch(API_CONFIG.apiBase + "/functions/v1/project-api", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
        body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "delete", collection: "${plural}", id }),
      });
      setItems(prev => prev.filter(item => item.id !== id));
    } catch (err) { setError(err.message); throw err; }
  }, []);

  useEffect(() => { fetchItems(); }, [fetchItems]);

  return { ${plural}: items, loading, error, refresh: fetchItems, create, update, remove };
}
`;
}

function generateAuthContext(projectId: string, apiBase: string): string {
  return `import React, { createContext, useContext, useState, useEffect, useRef } from "react";
import { API_CONFIG } from "../data/apiConfig";

const AuthContext = createContext(null);

// Session token stored in memory — NOT localStorage (security best practice)
let sessionToken = null;

export function AuthProvider({ children }) {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const mounted = useRef(true);

  useEffect(() => {
    mounted.current = true;
    // Restore session from project-auth "me" endpoint
    if (sessionToken) {
      fetch(API_CONFIG.apiBase + "/functions/v1/project-auth", {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
        body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "me", token: sessionToken }),
      })
        .then(r => r.json())
        .then(json => { if (mounted.current && json.user) setUser(json.user); })
        .catch(() => { sessionToken = null; })
        .finally(() => { if (mounted.current) setLoading(false); });
    } else {
      setLoading(false);
    }
    return () => { mounted.current = false; };
  }, []);

  const login = async (email, password) => {
    const resp = await fetch(API_CONFIG.apiBase + "/functions/v1/project-auth", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
      body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "login", email, password }),
    });
    const json = await resp.json();
    if (json.error) throw new Error(json.error);
    sessionToken = json.token;
    setUser(json.user);
    return json.user;
  };

  const signup = async (email, password, displayName) => {
    const resp = await fetch(API_CONFIG.apiBase + "/functions/v1/project-auth", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": "Bearer " + API_CONFIG.anonKey },
      body: JSON.stringify({ project_id: API_CONFIG.projectId, action: "signup", email, password, display_name: displayName }),
    });
    const json = await resp.json();
    if (json.error) throw new Error(json.error);
    sessionToken = json.token;
    setUser(json.user);
    return json.user;
  };

  const logout = () => {
    sessionToken = null;
    setUser(null);
  };

  return (
    <AuthContext.Provider value={{ user, loading, login, signup, logout, isAuthenticated: !!user }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error("useAuth must be used within AuthProvider");
  return ctx;
}
`;
}

function generateProtectedRoute(): string {
  return `import React from "react";
import { Navigate } from "react-router-dom";
import { useAuth } from "../../contexts/AuthContext";

export default function ProtectedRoute({ children }) {
  const { isAuthenticated, loading } = useAuth();
  if (loading) return <div className="flex items-center justify-center h-screen"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" /></div>;
  if (!isAuthenticated) return <Navigate to="/login" replace />;
  return children;
}
`;
}

// ─── AI-Enhanced Backend Generation ──────────────────────────────────────

async function generateBackendWithAI(
  task: any,
  domainModel: any,
  projectId: string,
  apiBase: string,
  existingFiles?: string[]
): Promise<{ files: Record<string, string>; chatText: string }> {
  // Fallback to template generation — AI enhancement can be added later
  // when we want more sophisticated hook logic (optimistic updates, caching, etc.)
  return generateBackendFiles(domainModel, projectId, apiBase);
}
